// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using reviewApi.Models;

#nullable disable

namespace reviewApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206050250_ud2")]
    partial class ud2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("reviewApi.Models.Department", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ParentCode")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Code");

                    b.HasIndex("ParentCode");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlow", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Code");

                    b.ToTable("EvaluationFlows");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("EvaluationFlowCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("EvaluationFlowCode");

                    b.ToTable("EvaluationFlowsDepartments");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EvaluationFlowCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("ParentId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationFlowCode");

                    b.HasIndex("ParentId");

                    b.HasIndex("RoleCode");

                    b.ToTable("EvaluationFlowsRoles");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationObject", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Code");

                    b.ToTable("EvaluationObjects");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationObjectRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EvaluationObjectCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationObjectCode");

                    b.HasIndex("UserId");

                    b.ToTable("EvaluationObjectRoles");
                });

            modelBuilder.Entity("reviewApi.Models.Role", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Code");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("reviewApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("RoleCode");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("reviewApi.Models.Department", b =>
                {
                    b.HasOne("reviewApi.Models.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCode");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowDepartment", b =>
                {
                    b.HasOne("reviewApi.Models.Department", "Department")
                        .WithMany("EvaluationFlowDepartments")
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.EvaluationFlow", "EvaluationFlow")
                        .WithMany("EvaluationFlowDepartments")
                        .HasForeignKey("EvaluationFlowCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("EvaluationFlow");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowRole", b =>
                {
                    b.HasOne("reviewApi.Models.EvaluationFlow", "EvaluationFlow")
                        .WithMany("EvaluationFlowRoles")
                        .HasForeignKey("EvaluationFlowCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.EvaluationFlowRole", "Parent")
                        .WithMany("Child")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.Role", "Role")
                        .WithMany("EvaluationFlowRoles")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationFlow");

                    b.Navigation("Parent");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationObjectRole", b =>
                {
                    b.HasOne("reviewApi.Models.EvaluationObject", "EvaluationObject")
                        .WithMany("EvaluationObjectRoles")
                        .HasForeignKey("EvaluationObjectCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.User", "User")
                        .WithMany("EvaluationObjectRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationObject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("reviewApi.Models.User", b =>
                {
                    b.HasOne("reviewApi.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("reviewApi.Models.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("EvaluationFlowDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlow", b =>
                {
                    b.Navigation("EvaluationFlowDepartments");

                    b.Navigation("EvaluationFlowRoles");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowRole", b =>
                {
                    b.Navigation("Child");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationObject", b =>
                {
                    b.Navigation("EvaluationObjectRoles");
                });

            modelBuilder.Entity("reviewApi.Models.Role", b =>
                {
                    b.Navigation("EvaluationFlowRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("reviewApi.Models.User", b =>
                {
                    b.Navigation("EvaluationObjectRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
