// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using reviewApi.Models;

#nullable disable

namespace reviewApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207120855_u5")]
    partial class u5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("reviewApi.Models.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("CriteriaSetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Max")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Min")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaSetId");

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("reviewApi.Models.Criteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("CriteriaSetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MaxScore")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("TypeScore")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("parentId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaSetId");

                    b.HasIndex("parentId");

                    b.ToTable("Criterias");
                });

            modelBuilder.Entity("reviewApi.Models.CriteriaSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("CriteriaSets");
                });

            modelBuilder.Entity("reviewApi.Models.CriteriaSetObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriteriaSetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EvaluationObjectCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaSetId");

                    b.HasIndex("EvaluationObjectCode");

                    b.ToTable("CriteriaSetObjects");
                });

            modelBuilder.Entity("reviewApi.Models.CriteriaSetPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriteriaSetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("month")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("year")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaSetId");

                    b.ToTable("CriteriaSetPeriods");
                });

            modelBuilder.Entity("reviewApi.Models.Department", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ParentCode")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Code");

                    b.HasIndex("ParentCode");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("reviewApi.Models.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriteriaSetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaSetId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("UserId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("ReplyToChatId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SenderId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("ReplyToChatId")
                        .IsUnique()
                        .HasFilter("\"ReplyToChatId\" IS NOT NULL");

                    b.HasIndex("SenderId");

                    b.ToTable("EvaluationChats");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationChatFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaluationChatId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationChatId");

                    b.ToTable("EvaluationChatFiles");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlow", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Code");

                    b.ToTable("EvaluationFlows");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("EvaluationFlowCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("EvaluationFlowCode");

                    b.ToTable("EvaluationFlowsDepartments");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EvaluationFlowCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationFlowCode");

                    b.HasIndex("ParentId");

                    b.HasIndex("RoleCode");

                    b.ToTable("EvaluationFlowsRoles");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationObject", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Code");

                    b.ToTable("EvaluationObjects");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationObjectRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EvaluationObjectCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationObjectCode");

                    b.HasIndex("UserId");

                    b.ToTable("EvaluationObjectRoles");
                });

            modelBuilder.Entity("reviewApi.Models.Role", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Code");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("reviewApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("RoleCode");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("reviewApi.Models.Classification", b =>
                {
                    b.HasOne("reviewApi.Models.CriteriaSet", "CriteriaSet")
                        .WithMany("Classifications")
                        .HasForeignKey("CriteriaSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriteriaSet");
                });

            modelBuilder.Entity("reviewApi.Models.Criteria", b =>
                {
                    b.HasOne("reviewApi.Models.CriteriaSet", "CriteriaSet")
                        .WithMany("Criterias")
                        .HasForeignKey("CriteriaSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.Criteria", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("parentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriteriaSet");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("reviewApi.Models.CriteriaSetObject", b =>
                {
                    b.HasOne("reviewApi.Models.CriteriaSet", "CriteriaSet")
                        .WithMany("CriteriaSetObjects")
                        .HasForeignKey("CriteriaSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.EvaluationObject", "EvaluationObject")
                        .WithMany("CriteriaSetObjects")
                        .HasForeignKey("EvaluationObjectCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriteriaSet");

                    b.Navigation("EvaluationObject");
                });

            modelBuilder.Entity("reviewApi.Models.CriteriaSetPeriod", b =>
                {
                    b.HasOne("reviewApi.Models.CriteriaSet", "CriteriaSet")
                        .WithMany("CriteriaSetPeriods")
                        .HasForeignKey("CriteriaSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriteriaSet");
                });

            modelBuilder.Entity("reviewApi.Models.Department", b =>
                {
                    b.HasOne("reviewApi.Models.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCode");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("reviewApi.Models.Evaluation", b =>
                {
                    b.HasOne("reviewApi.Models.CriteriaSet", "CriteriaSet")
                        .WithMany("Evaluations")
                        .HasForeignKey("CriteriaSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.User", "User")
                        .WithMany("Evaluations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriteriaSet");

                    b.Navigation("Manager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationChat", b =>
                {
                    b.HasOne("reviewApi.Models.Evaluation", "Evaluation")
                        .WithMany("EvaluationChats")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.EvaluationChat", "ReplyToChat")
                        .WithOne("Replies")
                        .HasForeignKey("reviewApi.Models.EvaluationChat", "ReplyToChatId");

                    b.HasOne("reviewApi.Models.User", "Sender")
                        .WithMany("EvaluationChats")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("ReplyToChat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationChatFile", b =>
                {
                    b.HasOne("reviewApi.Models.EvaluationChat", "EvaluationChat")
                        .WithMany("EvaluationChatFiles")
                        .HasForeignKey("EvaluationChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationChat");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowDepartment", b =>
                {
                    b.HasOne("reviewApi.Models.Department", "Department")
                        .WithMany("EvaluationFlowDepartments")
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.EvaluationFlow", "EvaluationFlow")
                        .WithMany("EvaluationFlowDepartments")
                        .HasForeignKey("EvaluationFlowCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("EvaluationFlow");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowRole", b =>
                {
                    b.HasOne("reviewApi.Models.EvaluationFlow", "EvaluationFlow")
                        .WithMany("EvaluationFlowRoles")
                        .HasForeignKey("EvaluationFlowCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.EvaluationFlowRole", "Parent")
                        .WithMany("Child")
                        .HasForeignKey("ParentId");

                    b.HasOne("reviewApi.Models.Role", "Role")
                        .WithMany("EvaluationFlowRoles")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationFlow");

                    b.Navigation("Parent");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationObjectRole", b =>
                {
                    b.HasOne("reviewApi.Models.EvaluationObject", "EvaluationObject")
                        .WithMany("EvaluationObjectRoles")
                        .HasForeignKey("EvaluationObjectCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.User", "User")
                        .WithMany("EvaluationObjectRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationObject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("reviewApi.Models.User", b =>
                {
                    b.HasOne("reviewApi.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("reviewApi.Models.Criteria", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("reviewApi.Models.CriteriaSet", b =>
                {
                    b.Navigation("Classifications");

                    b.Navigation("CriteriaSetObjects");

                    b.Navigation("CriteriaSetPeriods");

                    b.Navigation("Criterias");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("reviewApi.Models.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("EvaluationFlowDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("reviewApi.Models.Evaluation", b =>
                {
                    b.Navigation("EvaluationChats");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationChat", b =>
                {
                    b.Navigation("EvaluationChatFiles");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlow", b =>
                {
                    b.Navigation("EvaluationFlowDepartments");

                    b.Navigation("EvaluationFlowRoles");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowRole", b =>
                {
                    b.Navigation("Child");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationObject", b =>
                {
                    b.Navigation("CriteriaSetObjects");

                    b.Navigation("EvaluationObjectRoles");
                });

            modelBuilder.Entity("reviewApi.Models.Role", b =>
                {
                    b.Navigation("EvaluationFlowRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("reviewApi.Models.User", b =>
                {
                    b.Navigation("EvaluationChats");

                    b.Navigation("EvaluationObjectRoles");

                    b.Navigation("Evaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
